### ISSUE TITLE
Configuration population fails in strange ways when environmental variables aren't set

### ISSUE THREAD

**Issue by matthewfcarlson** [tianocore/edk2-pytool-extensions#110]
ERROR - Traceback (most recent call last):
  File "c:\git\edk2-pytool-extensions\edk2toolext\environment\uefi_build.py", line 109, in Go
    ret = self.SetEnv()
  File "c:\git\edk2-pytool-extensions\edk2toolext\environment\uefi_build.py", line 369, in SetEnv
    conf_mgmt.ConfMgmt().populate_conf_dir(conf_dir, self.UpdateConf, TemplateDirList)
  File "c:\git\edk2-pytool-extensions\edk2toolext\environment\conf_mgmt.py", line 58, in populate_conf_dir
    p = os.path.join(r, templatefiles[x])
  File "c:\python\3.7.2\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by spbrogan** [comment]
not actionable.  
closing for now.  
Re-open with details about how to repo if you want a fix.  
Thanks
