### ISSUE TITLE
Improve error message when Edk2ToolsBuild.py fails due to missing TOOL_CHAIN_TAG and -t option

### ISSUE THREAD

**Issue by out0xb2** [tianocore/edk2-pytool-extensions#122]
When I call Edk2ToolsBuild.py without the -t option or pass a missing tool chain tag, the error message is unhelpful.

Not really an extension issue, but related to building BaseTools the Pytool way.

Example when specifying an incorrect -t option
'''
(venv_pytools_dev) C:\git\edk2_ovmf\BaseTools>python Edk2ToolsBuild.py -t VS2015x86
SECTION - Init SDE
SECTION - Loading Plugins
SECTION - Start Invocable Tool
Traceback (most recent call last):
  File "Edk2ToolsBuild.py", line 163, in <module>
    main()
  File "Edk2ToolsBuild.py", line 159, in main
    Edk2ToolsBuild().Invoke()
  File "c:\git\edk2-pytool-extensions\edk2toolext\base_abstract_invocable.py", line 141, in Invoke
    retcode = self.Go()
  File "Edk2ToolsBuild.py", line 120, in Go
    interesting_keys, 'x86', vs_version=self.tool_chain_tag.lower())
  File "c:\git\edk2-pytool-library\edk2toollib\windows\locate_tools.py", line 172, in QueryVcVariables
    raise ValueError("Bad VC")
ValueError: Bad VC
'''

Better example to follow...

**Comment by Navdeep5160** [comment]
How were u able to fix these issues.
I am not talking about improvement, but the issues like BAD VC and all.

Issues I am facing
c:\edk2\BaseTools>python Edk2ToolsBuild.py -t VS2019
SECTION - Init SDE
SECTION - Loading Plugins
SECTION - Start Invocable Tool
Traceback (most recent call last):
  File "Edk2ToolsBuild.py", line 177, in <module>
    main()
  File "Edk2ToolsBuild.py", line 173, in main
    Edk2ToolsBuild().Invoke()
  File "C:\Program Files\Python38\lib\site-packages\edk2toolext\base_abstract_invocable.py", line 141, in Invoke
    retcode = self.Go()
  File "Edk2ToolsBuild.py", line 139, in Go
    raise Exception("Failed to build.")
Exception: Failed to build.

**Comment by out0xb2** [comment]
@Navdeep5160 , you are reporting a different issue.  Feel free to create a new Issue.  @matthewfcarlson for quick triage ideas.

**Comment by matthewfcarlson** [comment]
@Navdeep5160 mind adding more of your build log? It looks like the line that's failing is the call to nmake.

**Comment by matthewfcarlson** [comment]
I'm moving this conversation to: https://github.com/tianocore/edk2-pytool-extensions/issues/180

**Comment by Javagedes** [comment]
Moving this to edk2-pytool-library to improve error messages in edk2toollib/windows/locate_tools.py
