### ISSUE TITLE
Support non-valued BLD defines, e.g. "-D E1000_ENABLE" without =<foo>

### ISSUE THREAD

**Issue by out0xb2** [tianocore/edk2-pytool-extensions#128]
The EDK2 [OvmfPkg README](https://github.com/tianocore/edk2/blob/master/OvmfPkg/README) instructs users to add non-valued "-D" defines to enable features.  

OvmfPkg/README:
>  - Add "-D E1000_ENABLE" to your build command (only when building
>      "OvmfPkg/OvmfPkgIa32X64.dsc" or "OvmfPkg/OvmfPkgX64.dsc").
>    - For example: "build -D E1000_ENABLE".

stuart_build throws an exception if I do not pass a `=<value>` in a BLD_ parameter, for example:

```
stuart_build -c PlatformBuild.py BLD_*_E1000_ENABLE

Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\git\venv_pytools\Scripts\stuart_build.exe\__main__.py", line 7, in <module>
  File "c:\git\venv_pytools\lib\site-packages\edk2toolext\invocables\edk2_platform_build.py", line 141, in main
    Edk2PlatformBuild().Invoke()
  File "c:\git\venv_pytools\lib\site-packages\edk2toolext\base_abstract_invocable.py", line 107, in Invoke
    self.ParseCommandLineOptions()
  File "c:\git\venv_pytools\lib\site-packages\edk2toolext\edk2_invocable.py", line 203, in ParseCommandLineOptions
    raise RuntimeError(f"Unknown variable passed in via CLI: {argument}")
RuntimeError: Unknown variable passed in via CLI: BLD_*_E1000_ENABLE
```

A workaround is to specify a dummy value **`=1`**, for example:
`stuart_build -c PlatformBuild.py BLD_*_E1000_ENABLE=1`

**Comment by Javagedes** [comment]
I've added PR #372 to resolve this. It enabled non-valued regular and build variables from the command line.

**Comment by Javagedes** [comment]
Per external conversation, need to look into setting the value to something other than "TRUE" so that it cannot be matched against.
