### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [tianocore/edk2-pytool-extensions#188]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.13.4. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary edk2-pytool-extensions -w /tmp/ext edk2-pytool-extensions==0.13.4
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting edk2-pytool-extensions==0.13.4
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/de4/e387bd6b1db11/edk2-pytool-extensions-0.13.4.tar.gz (2.4 MB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-2zor5kx8/edk2-pytool-extensions/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-2zor5kx8/edk2-pytool-extensions/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-2zor5kx8/edk2-pytool-extensions/pip-egg-info
         cwd: /tmp/pip-wheel-2zor5kx8/edk2-pytool-extensions/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-2zor5kx8/edk2-pytool-extensions/setup.py", line 15, in <module>
        with open("readme.md", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'readme.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by spbrogan** [comment]
Agree.  Thanks for submitting. 

After looking at this a little closer we need to clean up the manifest and the sdist build process.  We are publishing lots of images and useless files for a source distribution.

**Comment by spbrogan** [comment]
info: https://docs.python.org/3/distutils/sourcedist.html

**Comment by thatch** [comment]
I sent a PR as a starting point, in case that's helpful.
