### ISSUE TITLE
Omnicache path check causes failure when not set

### ISSUE THREAD

**Issue by spbrogan** [tianocore/edk2-pytool-extensions#80]
Error when not set.

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.4/x64/bin/stuart_setup", line 10, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.7.4/x64/lib/python3.7/site-packages/edk2toolext/invocables/edk2_setup.py", line 219, in main
    Edk2PlatformSetup().Invoke()
  File "/opt/hostedtoolcache/Python/3.7.4/x64/lib/python3.7/site-packages/edk2toolext/base_abstract_invocable.py", line 105, in Invoke
    self.ParseCommandLineOptions()
  File "/opt/hostedtoolcache/Python/3.7.4/x64/lib/python3.7/site-packages/edk2toolext/edk2_invocable.py", line 187, in ParseCommandLineOptions
    self.RetrieveCommandLineOptions(args)
  File "/opt/hostedtoolcache/Python/3.7.4/x64/lib/python3.7/site-packages/edk2toolext/invocables/edk2_setup.py", line 84, in RetrieveCommandLineOptions
    if (not os.path.exists(self.omnicache_path)):
  File "/opt/hostedtoolcache/Python/3.7.4/x64/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
##[error]/opt/hostedtoolcache/Python/3.7.4/x64/bin/stuart_setup failed with return code: 1

**Comment by matthewfcarlson** [comment]
Fixed by #79
