### ISSUE TITLE
ConfMgmt fails 

### ISSUE THREAD

**Issue by spbrogan** [tianocore/edk2-pytool-extensions#9]

**Comment by spbrogan** [comment]
Error:

CRITICAL - Build Process Exception
ERROR - Traceback (most recent call last):
  File "c:\src\1905\venv\lib\site-packages\edk2toolext\environment\uefi_build.py", line 109, in Go
    ret = self.SetEnv()
  File "c:\src\1905\venv\lib\site-packages\edk2toolext\environment\uefi_build.py", line 372, in SetEnv
    ret = e.ToolsDefConfigure()
  File "c:\src\1905\venv\lib\site-packages\edk2toolext\environment\conf_mgmt.py", line 179, in ToolsDefConfigure
    if (not self.VisualStudioSpecificVersions(Tag)):
  File "c:\src\1905\venv\lib\site-packages\edk2toolext\environment\conf_mgmt.py", line 228, in VisualStudioSpecificVersions
    ipath = GetVsInstallPath(ToolChainTag.lower(), "VS150INSTALLPATH")
  File "c:\src\1905\venv\lib\site-packages\edk2toolext\environment\conf_mgmt.py", line 192, in GetVsInstallPath
    path = shell_environment.ShellEnvironment.get_shell_var(varname)
TypeError: get_shell_var() missing 1 required positional argument: 'var_name'
